sudo: required
dist: trusty
language: go
go:
  - 1.6

# TODO: git rev-parse HEAD on the gomobile installation
before_install:
  - sudo apt-get update -qq
  - sudo apt-cache search libgles2-mesa-dev
  - sudo apt-get install libgles2-mesa-dev
  - go get golang.org/x/mobile/cmd/gomobile
  - gomobile init

# The default install step for Go on Travis seems
# to be "go get -t -v ./...".
# However, that seems to yield errors such as
# https://travis-ci.org/asimshankar/triangles/builds/143616878
# Try what is specified in README.md
install:
  - go get github.com/asimshankar/triangles

script:
  - go test ./...
  - gomobile build -target=android .
