language: go

go:
  - 1.6

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgles2-mesa-dev
  - go get golang.org/x/mobile/cmd/gomobile
  - gomobile init
  - ls /usr/include/GLES3

# The default install step for Go on Travis seems
# to be "go get -t -v ./...".
# However, that seems to yield errors such as
# https://travis-ci.org/asimshankar/triangles/builds/143616878
# Try what is specified in README.md
install:
  - go get github.com/asimshankar/triangles

script:
  - go build .
  - go test ./...
  - gomobile build -target=android .
