// This file was auto-generated by the vanadium vdl tool.
// Source: spec.vdl

// Package spec defines the interfaces between networked participants of the
// triagles display.
//   go get v.io/x/ref/cmd/vdl
//   VDLPATH=$GOPATH/src $GOPATH/bin/vdl --builtin_vdlroot generate github.com/asimshankar/triangles/spec
package spec

import (
	// VDL system imports
	"v.io/v23/vdl"
)

// Triangle represents a triangle that will be displayed on the screen.
//
// The coordinates (X, Y) and velocity (Dx, Dy) are in a world where
// (0, 0) is the center, (1, 1) is the top right and (-1, -1) is the bottom
// left.
//
// R, G, B denote the color of the triangle.
type Triangle struct {
	X  float32
	Y  float32
	Dx float32
	Dy float32
	R  float32
	G  float32
	B  float32
}

func (Triangle) __VDLReflect(struct {
	Name string `vdl:"github.com/asimshankar/triangles/spec.Triangle"`
}) {
}

func init() {
	vdl.Register((*Triangle)(nil))
}
